// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUtKo9K6Trzn-Lq7JCJb-FponehYxLAbM',
    appId: '1:994301263812:android:4659d8179d2e280b75ee91',
    messagingSenderId: '994301263812',
    projectId: 'expense-tracker-ab4ec',
    storageBucket: 'expense-tracker-ab4ec.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCralq63UDHShQ6IQFqnVKX3MJcy8KK6G0',
    appId: '1:994301263812:web:2530b0cae909a55e75ee91',
    messagingSenderId: '994301263812',
    projectId: 'expense-tracker-ab4ec',
    authDomain: 'expense-tracker-ab4ec.firebaseapp.com',
    storageBucket: 'expense-tracker-ab4ec.firebasestorage.app',
    measurementId: 'G-JQER51BVR9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBhTxtNLWLxxSpWTX3Ea4WZFVIq81F46U',
    appId: '1:994301263812:ios:0bff92ca4903c7c175ee91',
    messagingSenderId: '994301263812',
    projectId: 'expense-tracker-ab4ec',
    storageBucket: 'expense-tracker-ab4ec.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBhTxtNLWLxxSpWTX3Ea4WZFVIq81F46U',
    appId: '1:994301263812:ios:0bff92ca4903c7c175ee91',
    messagingSenderId: '994301263812',
    projectId: 'expense-tracker-ab4ec',
    storageBucket: 'expense-tracker-ab4ec.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCralq63UDHShQ6IQFqnVKX3MJcy8KK6G0',
    appId: '1:994301263812:web:87fb3bd8c9f03e4975ee91',
    messagingSenderId: '994301263812',
    projectId: 'expense-tracker-ab4ec',
    authDomain: 'expense-tracker-ab4ec.firebaseapp.com',
    storageBucket: 'expense-tracker-ab4ec.firebasestorage.app',
    measurementId: 'G-FR63E1HFCM',
  );
}
